spring:
  cloud:
    stream:
      bindings:
          input:
                  destination: advertisementChangeTopic
                  content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost


